// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AiePcGhe9_ipTGuvcmK_IwMnh1Upz3I',
    appId: '1:208069710956:web:afd410a655728232653449',
    messagingSenderId: '208069710956',
    projectId: 'my-world-in',
    authDomain: 'my-world-in.firebaseapp.com',
    storageBucket: 'my-world-in.appspot.com',
    measurementId: 'G-4VC63LPV6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-s1lrrvk4t1EUxWvcaPbCbcOutH5QJpI',
    appId: '1:208069710956:android:2d841da53901178c653449',
    messagingSenderId: '208069710956',
    projectId: 'my-world-in',
    storageBucket: 'my-world-in.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPNduMnRl_ceyQihKFsXklCmEIMMpcaY',
    appId: '1:208069710956:ios:3fe64dc8d230abe3653449',
    messagingSenderId: '208069710956',
    projectId: 'my-world-in',
    storageBucket: 'my-world-in.appspot.com',
    iosClientId: '208069710956-thd8vq9qomdgt3fteb1osvh07alm6kbb.apps.googleusercontent.com',
    iosBundleId: 'com.myworld.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoPNduMnRl_ceyQihKFsXklCmEIMMpcaY',
    appId: '1:208069710956:ios:3fe64dc8d230abe3653449',
    messagingSenderId: '208069710956',
    projectId: 'my-world-in',
    storageBucket: 'my-world-in.appspot.com',
    iosClientId: '208069710956-thd8vq9qomdgt3fteb1osvh07alm6kbb.apps.googleusercontent.com',
    iosBundleId: 'com.myworld.ui',
  );
}
